### ISSUE TITLE
apostrophe's in time query

### ISSUE THREAD

**Issue by macg-gh** [ccarrster/hackinghealth2019#19]
Line 14 of edit.php adds an apostrophe to the field, which causes SQL to not like it:
			$start = "'".$date . ' ' . $time . ':00'."'";

If you take out the apostrophes at the beginning and the end it will work:
                        $start = $date . ' ' . $time . ':00';

I did this locally and could add an event. I confirmed with a manual query and noticed edit.php now shows the events.

**Comment by ccarrster** [comment]
Good one.
